config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root "lists#index"
  get 'home/trash'
  get 'home/trash_all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def trash
		@trash = List.where(:completed => true).destroy_all
		redirect_to lists_url, notice: 'Bitmiş olan Yapılacaklar silindi.'
	end

	def trash_all
		@trash_all = List.all.destroy_all
		redirect_to lists_url, notice: 'Bütün liste silindi.'
	end



end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @list = List.new
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url, notice: 'Yapılacak oluşturuldu.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url, notice: 'Yapılacak güncellendi.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'Yapılacak silindi.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>
    <%= render 'navbar', list: @list %>
    <div class="container">
      <%= render 'flash' %>
      <%= yield %>
      

    </div>
  </body>
</html>

app/views/lists/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
		<div class="alert alert-warning alert-dismissible">
			<a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<%= content_tag(:div, msg) %>
		</div>
<% end %>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label "Bitti mi?" %>
    <%= form.check_box :completed, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Yapılacağı Güncelle", class: 'btn btn-info' %>
  </div>
<% end %>

app/views/lists/_form_index.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline my-2 my-lg-0">
    <%= form.text_field :description, class: "fform-control mr-sm-2" %>
    <%= form.submit "Yapılacak Ekle", class: "btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Yapılacaklar Listem", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <%= render 'form_index', list: @list %>
  </div>
</nav>

app/views/lists/edit.html.erb
<center>
	<h1>Yapılacağı Düzenle</h1>
	<br/>
	<div class="card" style="width: 50rem;">
	  <div class="card-body">
	   <%= render 'form', list: @list %>
	  </div>
	</div>

	<br></br>

	<% link_to 'Göster', @list %> 
	<%= link_to 'Geri', lists_path %>
</center>

app/views/lists/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Yapılacaklar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <body>
    <% @lists.each do |list| %>
      <% if list.completed %>
        <tr class="bg-light">
          <td class="striker"><%= link_to list.description, edit_list_path(list) %><% list.description %></td>
          <td>
            <%= form_with(model: list, local: true) do |form| %>
              <%= form.text_field :description, type: 'hidden' %>
              <%= form.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
              <%= form.submit "Bitmedi", class: 'btn btn-info' %>
            <% end %>
          </td>
          <td>
            <% link_to 'Göster', list %>
            <center><%= link_to 'Sil', list, class: 'btn btn-dark', method: :delete, data: { confirm: 'Emin misin?', class: 'btn btn-light' } %></center>
          </td>
        </tr>
      <% else %>
        <tr>
          <td><%= link_to list.description, edit_list_path(list) %><% list.description %></td>
          <td>
            <%= form_with(model: list, local: true) do |form| %>
              <%= form.text_field :description, type: 'hidden' %>
              <%= form.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
              <%= form.submit "Bitti", class: 'btn btn-info' %>
            <% end %>
          </td>
          <td>
            <% link_to 'Göster', list %>
            <center><%= link_to 'Sil', list, class: 'btn btn-dark', method: :delete, data: { confirm: 'Emin misin?', class: 'btn btn-light' } %></center>
          </td>
        </tr>

      <% end %>
    <% end %>
  </tbody>
</table>

<br>


<% link_to 'Yapılacak ekle', new_list_path, class: 'btn btn-success' %>



<%= link_to 'Yapılmış olanları Sil', home_trash_path, class: 'btn btn-warning btn-lg float-left', data: { confirm: 'Emin misin?' } %> 

<%= link_to 'Hepsini Sil', home_trash_all_path, class: 'btn btn-danger btn-lg float-right', data: { confirm: 'Emin misin?'} %>

app/views/lists/new.html.erb
<h1>Yeni Yapılacak Ekle</h1>

<%= render 'form', list: @list %>

<%= link_to 'Geri', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Yapılacak:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Bitti mi?:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Düzenle', edit_list_path(@list) %> |
<%= link_to 'Geri', lists_path %>